#pragma once

#define UASSET_JSON_EXPORTER_VERSION_MAJOR 1
#define UASSET_JSON_EXPORTER_VERSION_MINOR 9
#define UASSET_JSON_EXPORTER_VERSION_PATCH 0
#define UASSET_JSON_EXPORTER_VERSION_STRING TEXT("1.9.0")
